# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-19 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='physicaldevice',
            options={'ordering': ['status'], 'verbose_name': '\u7269\u7406\u8d44\u4ea7\u4fe1\u606f', 'verbose_name_plural': '\u7269\u7406\u8d44\u4ea7\u4fe1\u606f'},
        ),
        migrations.AddField(
            model_name='physicaldevice',
            name='status',
            field=models.IntegerField(choices=[(0, '\u6b63\u5e38'), (1, '\u5df2\u62a5\u5e9f')], default=0, verbose_name='\u8bbe\u5907\u72b6\u6001'),
        ),
    ]
