# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-19 06:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20180419_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetidc',
            name='customer_name',
        ),
    ]
