# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-19 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_remove_assetidc_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetidc',
            name='bandwidth_cost',
            field=models.IntegerField(blank=True, max_length=32, null=True, verbose_name='\u5e26\u5bbd\u8d39\u7528'),
        ),
        migrations.AddField(
            model_name='assetidc',
            name='pod_cost',
            field=models.IntegerField(blank=True, max_length=32, null=True, verbose_name='\u673a\u67dc\u8d39\u7528'),
        ),
    ]
