# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-19 08:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0008_auto_20180419_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicaldevice',
            name='brand',
        ),
        migrations.AlterField(
            model_name='physicaldevice',
            name='asset_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u8bbe\u5907\u7ba1\u7406\u5458'),
        ),
        migrations.AlterField(
            model_name='physicaldevice',
            name='asset_cab',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='\u8bbe\u5907\u6240\u5728\u673a\u67dc'),
        ),
        migrations.AlterField(
            model_name='physicaldevice',
            name='asset_cab_location',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='\u8bbe\u5907\u6240\u5728\u673a\u67dc\u4f4d\u7f6e'),
        ),
        migrations.AlterField(
            model_name='physicaldevice',
            name='asset_idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.AssetIDC', verbose_name='\u8bbe\u5907\u6240\u5728IDC'),
        ),
        migrations.AlterField(
            model_name='physicaldevice',
            name='asset_manage_dep',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='\u8bbe\u5907\u7ba1\u7406\u90e8\u95e8'),
        ),
        migrations.AlterField(
            model_name='physicaldevice',
            name='asset_owner_dep',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='\u8bbe\u5907\u6240\u6709\u90e8\u95e8'),
        ),
        migrations.AlterField(
            model_name='physicaldevice',
            name='asset_use_dep',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='\u8bbe\u5907\u4f7f\u7528\u90e8\u95e8'),
        ),
        migrations.AlterField(
            model_name='physicaldevice',
            name='decription',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='\u8bbe\u5907\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='physicaldevice',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='\u91c7\u8d2d\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='physicaldevice',
            name='vendor',
            field=models.CharField(max_length=16, verbose_name='\u8bbe\u5907\u5382\u5546'),
        ),
    ]
