# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0009_auto_20180419_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicaldevice',
            name='sn',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='\u8bbe\u5907\u5e8f\u5217\u53f7'),
        ),
    ]
