# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='passmgr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('bpasswd1', models.CharField(default='', max_length=64)),
                ('bpasswd2', models.CharField(default='', max_length=64)),
                ('bpasswd3', models.CharField(default='', max_length=64)),
                ('host', models.CharField(default='', max_length=64)),
                ('descript', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
